# Generated by Django 4.2.6 on 2023-11-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feature_alter_servico_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('expense', models.CharField(max_length=100, verbose_name='Expense')),
                ('description', models.TextField(max_length=200, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete'), ('lni-laptop-phone', 'devices'), ('lni-leaf', 'folha'), ('lni-package', 'caixa'), ('lni-drop', 'gota'), ('lni-star', 'estrela')], max_length=16, verbose_name='Icone')),
                ('date', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField(verbose_name='Valor')),
                ('category', models.CharField(choices=[('combustivel', 'Combustível'), ('mecanica', 'Mecânica'), ('alimentacao', 'Alimentação'), ('devocional', 'Devocional'), ('recreacao', 'Recreação')], max_length=16, verbose_name='Categoria')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
    ]
